#ifndef BOARD_RP2040_ZERO_CONFIG_H
#define BOARD_RP2040_ZERO_CONFIG_H

#define PROBE_IO_RAW
#define PROBE_CDC_UART

#define PROBE_PIN_RESET 4

#define PROBE_SM 0
#define PROBE_PIN_OFFSET 2
#define PROBE_PIN_SWCLK (PROBE_PIN_OFFSET + 0)
#define PROBE_PIN_SWDIO (PROBE_PIN_OFFSET + 1)

#define PROBE_UART_TX 20
#define PROBE_UART_RX 21
#define PROBE_UART_INTERFACE uart1
#define PROBE_UART_BAUDRATE 115200

#define PROBE_USB_CONNECTED_LED 25

#define PROBE_PRODUCT_STRING "Debugprobe (CMSIS-DAP)"

#endif
